// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function LoadImgBase64(arg1:string,arg2:string):Promise<string>;

export function LoadMD():Promise<model.MDInfo>;
